export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const ERROR = 'ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILURE = 'OTP_FAILURE';
export const FETCH_OTP = 'FETCH_OTP';
export const LOGIN_OTP = 'LOGIN_OTP';

export const SET_ITEMS = 'SET_ITEMS';
export const SET_ITEMS_SUCCESS = 'SET_ITEMS_SUCCESS';
export const SET_ITEMS_ERROR = 'SET_ITEMS_ERROR';

export const SET_ITEMDETAILS = 'SET_ITEMDETAILS';
export const SET_ITEMDETAILS_SUCCESS = 'SET_ITEMDETAILS_SUCCESS';
export const SET_ITEMDETAILS_ERROR = 'SET_ITEMDETAILS_ERROR';

export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEMS_SUCCESS = 'UPDATE_ITEMS_SUCCESS';
export const UPDATE_ITEMS_ERROR = 'UPDATE_ITEMS_ERROR';
export const UPDATE_ITEM = 'ITEM';

export const SELECTED_ITEM = 'SELECTED_ITEM';
export const SELECTED_ITEM_SUCCESS = 'SELECTED_ITEM_SUCCESS';
export const SELECTED_ITEM_ERROR = 'SELECTED_ITEM_ERROR';

export const SELECTED_ITEMDETAIL = 'SELECTED_ITEMDETAIL';
export const SELECTED_ITEMDETAIL_SUCCESS = 'SELECTED_ITEMDETAIL_SUCCESS';
export const SELECTED_ITEMDETAIL_ERROR = 'SELECTED_ITEMDETAIL_ERROR';

export const GET_ITEMDETAILS = 'GET_ITEMDETAILS';
export const GET_ITEMDETAILS_SUCCESS = 'GET_ITEMDETAILS_SUCCESS';
export const GET_ITEMDETAILS_ERROR = 'GET_ITEMDETAILS_ERROR';
export const CREATE_ITEMDETAIL_SUCCESS = 'CREATE_ITEMDETAIL_SUCCESS';
export const CREATE_ITEMDETAIL_ERROR = 'CREATE_ITEMDETAIL_ERROR';
export const CREATE_ITEMDETAIL = 'CREATE_ITEMDETAIL';
export const UPDATE_ITEMDETAIL_SUCCESS = 'UPDATE_ITEMDETAIL_SUCCESS';
export const UPDATE_ITEMDETAIL_ERROR = 'UPDATE_ITEMDETAIL_ERROR';
export const UPDATE_ITEMDETAIL = 'ITEMDETAIL';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const CREATE_USERS_ERROR = 'CREATE_USERS_ERROR';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_ERROR = 'UPDATE_USERS_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
